version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wordpulse-stack"
s3_bucket = "YOUR_S3_BUCKET_NAME"
s3_prefix = "wordpulse"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"