AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dictionary API using AWS Lambda

Resources:
  DictionaryApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: dictionary-api.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"